# -*- coding: utf-8 -*-
"""Machine learning with zafar iqbal sb and digiskills.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q5zPg4-_nBTMVhP2Qv_w03kkBz_Mm_vl
"""

# Calcute Price by Milege

# Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

# Import DataSet
df = pd.read_excel('/content/drive/MyDrive/AI ML Zafar Iqbal sb/datasets/1. car price.xlsx')
df

# Visualize DataSet
plt.xlabel('Mileage', color = "red")
plt.ylabel('Price',   color = "red")
plt.scatter(df.Mileage, df.Price)

# Fit the Model
lr = linear_model.LinearRegression()
lr.fit(df[['Mileage']], df.Price)

# Get the Prediction from train model by giving (X)
lr.predict([[10000]])

# Check the Score
lr.score(df[['Mileage']], df.Price)

# Get coefficient (W)
lr.coef_

# Get Intercept (B)
lr.intercept_

# y = WX + B
-5 * 10000 + 2000000.0

# Plot the Line
plt.xlabel('Mileage', color = "red")
plt.ylabel('Price',   color = "red")
plt.scatter(df.Mileage, df.Price)
plt.plot(df.Mileage, lr.predict(df[['Mileage']]), color = "red")

# Calculte fare by Distance

# Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

# Import DataSet
df = pd.read_excel('/content/drive/MyDrive/AI ML Zafar Iqbal sb/datasets/2. fare calculation.xlsx')
df

# Visualize DataSet
plt.xlabel('Distance', color = "red")
plt.ylabel('Fare',   color = "red")
plt.scatter(df.Distance, df.Fare)

# Fit the Model
lr = linear_model.LinearRegression()
lr.fit(df[['Distance']], df.Fare)

# Get the Prediction from train model by giving (X)
lr.predict([[200]])

# Check the Score
lr.score(df[['Distance']], df.Fare)

# Get coefficient (W)
lr.coef_

# Get Intercept (B)
lr.intercept_

# y = W     X  +        B
y   = 20 *  + 100.00000000000
y

# Plot the Line
plt.xlabel('Distance', color = "red")
plt.ylabel('Fare',   color = "red")
plt.scatter(df.Distance, df.Fare)
plt.plot(df.Distance, lr.predict(df[['Distance']]), color = "red")

